---
title: "Análisis de supervivencia"
author: "Yessica Ortega"
date: '2022-06-25'
output: html_document
---
## Habilitar librerías
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(ggplot2)
library(readxl)
library(survminer)
library(ggpubr)
library(dplyr)
library(tidyverse)
```

## Importar, explorar set de datos y transformar variables de sobrevivencia
```{r}
mortalidad <- read_excel("data_mortalidad.xls", sheet = 2)
View(mortalidad)
head(mortalidad)
str(mortalidad)
summary(mortalidad)

# Convertir a factor la variable "tratamiento"
mortalidad$tratamiento<-as.factor(mortalidad$tratamiento)
mortalidad$fish_id<-as.factor(mortalidad$fish_id)
str(mortalidad)
```


## Planteamiento de hipótesis

```{r cars}
# H0 : La sobrevivencia en trucha arcoíris con o sin tratamiento no es diferente
# H1 : La sobrevivencia en trucha arcoíris con o sin tratamiento es diferente.
```

## Análisis de sobrevivencia
```{r}
# Creando objeto tipo sobrevivencia
surv_obj <- Surv(mortalidad$survival_time, mortalidad$survival_status)
class(surv_obj)
surv_obj

# Calculando la probabilidad de sobrevivencia de Kaplan-Meier y otras.
ps <- survfit(Surv(survival_time, survival_status) ~ tratamiento,
              data=mortalidad, na.action= na.exclude,type="kaplan-meier")
class(ps)
summary(ps)

# Probando si existen o no diferencias entre dos o más curvas de sobrevivencia
test_surv <- survdiff(formula=Surv(survival_time, survival_status) ~ tratamiento, data=mortalidad)
class(test_surv)
```

## Gráfica de sobrevivencia
```{r pressure, echo=TRUE}
ggsurvplot(ps, data=mortalidad, conf.int = FALSE, pval = TRUE, ggtheme = theme_bw())
```


